### ISSUE TITLE
demo.py error

### ISSUE THREAD

**Issue by chenkaixin66** [mkocabas/EpipolarPose#47]
When I run demo.py , the error happened.

Traceback (most recent call last):
  File "C:/Users/123/Desktop/EpipolarPose-master/EpipolarPose-master/demo.py", line 62, in <module>
    ****ax = fig.add_subplot('122', projection='3d', aspect=1)****
  File "F:\ana\lib\site-packages\matplotlib\figure.py", line 1414, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "F:\ana\lib\site-packages\matplotlib\axes\_subplots.py", line 69, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "F:\ana\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 101, in __init__
    super().__init__(fig, rect, frameon=True, *args, **kwargs)
  File "F:\ana\lib\site-packages\matplotlib\axes\_base.py", line 509, in __init__
    self.update(kwargs)
  File "F:\ana\lib\site-packages\matplotlib\artist.py", line 974, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "F:\ana\lib\site-packages\matplotlib\artist.py", line 974, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "F:\ana\lib\site-packages\matplotlib\artist.py", line 971, in _update_property
    return func(v)
  File "F:\ana\lib\site-packages\matplotlib\axes\_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

**Comment by crowdin001** [comment]
先把那个3D的注释掉，先看2D能不能成功运行，然后你再改改3D显示的语句。

**Comment by mzy12345678** [comment]
@chenkaixin66 
Hello, where is the demo.py file? I only found demo.ipynb.py

**Comment by khw11044** [comment]
ax = fig.add_subplot('122', projection='3d', aspect='auto')
